### ISSUE TITLE
Fails to load LWJGL on some machines

### ISSUE THREAD

**Issue by Blaarkies** [Blaarkies/Volynov#41]
**Describe the bug**

**To Reproduce**
Run the release build on a machine with a long environment variables PATH

**Expected behavior**
Game should load into main menu. Command prompt should show:
```
C:\DEV\boris\Volynov\build\Volynov-0.0.0>java -Dorg.lwjgl.util.Debug=true -jar .\volynov-0.0.0-uber.jar
[LWJGL] Version: 3.2.3 SNAPSHOT
[LWJGL]          OS: Windows 10 v10.0
[LWJGL]         JRE: 11.0.5 amd64
[LWJGL]         JVM: OpenJDK 64-Bit Server VM v11.0.5+10-b520.17 by JetBrains s.r.o
[LWJGL] Loading JNI library: lwjgl
[LWJGL]         Module: org.lwjgl
[LWJGL]         Loaded from org.lwjgl.librarypath: C:\Users\pierr\AppData\Local\Temp\lwjglpierr\3.2.3-SNAPSHOT\lwjgl.dll
[LWJGL] Loading library: jemalloc
[LWJGL]         Module: org.lwjgl.jemalloc
[LWJGL]         Loaded from org.lwjgl.librarypath: C:\Users\pierr\AppData\Local\Temp\lwjglpierr\3.2.3-SNAPSHOT\jemalloc.dll
[LWJGL] MemoryUtil allocator: JEmallocAllocator
[LWJGL] Loading library: glfw
[LWJGL]         Module: org.lwjgl.glfw
[LWJGL]         Loaded from org.lwjgl.librarypath: C:\Users\pierr\AppData\Local\Temp\lwjglpierr\3.2.3-SNAPSHOT\glfw.dll
[LWJGL] Loading JNI library: lwjgl_opengl
[LWJGL]         Module: org.lwjgl.opengl
[LWJGL]         Loaded from org.lwjgl.librarypath: C:\Users\pierr\AppData\Local\Temp\lwjglpierr\3.2.3-SNAPSHOT\lwjgl_opengl.dll
[LWJGL] Loading library: opengl32
[LWJGL]         Module: org.lwjgl.opengl
[LWJGL]         opengl32.dll not found in org.lwjgl.librarypath=C:\Users\pierr\AppData\Local\Temp\lwjglpierr\3.2.3-SNAPSHOT
[LWJGL]         Loaded from system paths: C:\Windows\SYSTEM32\opengl32.dll
[LWJGL] [GL] GL_ARB_shader_subroutine was reported as available but an entry point is missing.
[LWJGL] Loading JNI library: lwjgl_stb
[LWJGL]         Module: org.lwjgl.stb
[LWJGL]         Loaded from org.lwjgl.librarypath: C:\Users\pierr\AppData\Local\Temp\lwjglpierr\3.2.3-SNAPSHOT\lwjgl_stb.dll

C:\DEV\boris\Volynov\build\Volynov-0.0.0>pause
Press any key to continue . . .
```

**Screenshots**
```
C:\Users\boris\Downloads\volynov\build\Volynov-0.0.0>java -Dorg.lwjgl.util.Debug=true -jar .\volynov-0.0.0-uber.jar
[LWJGL] Version: 3.2.3 SNAPSHOT
[LWJGL]          OS: Windows 10 v10.0
[LWJGL]         JRE: 1.8.0_251 x86
[LWJGL]         JVM: Java HotSpot(TM) Client VM v25.251-b08 by Oracle Corporation
[LWJGL] Loading JNI library: lwjgl
[LWJGL]         Module: org.lwjgl
[LWJGL]         windows/x86/org/lwjgl/lwjgl.dll not found in java.library.path=C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Git\cmd;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\HashiCorp\Vagrant\bin;C:\Ruby26-x64\bin;C:\Users\boris\AppData\Local\Programs\Python\Python37-32\Scripts\;C:\Users\boris\AppData\Local\Programs\Python\Python37-32\;C:\Users\boris\AppData\Local\Microsoft\WindowsApps;.
[LWJGL]         lwjgl.dll not found in java.library.path
[LWJGL] Failed to load a library. Possible solutions:
        a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
        b) Add the JAR that contains the shared library to the classpath.
kotlin.UninitializedPropertyAccessException: lateinit property vertices has not been initialized
        at display.graphic.Renderer.dispose(Renderer.kt:139)
        at app.AppLogic.cleanup(AppLogic.kt:38)
        at app.AppRunner.run(AppRunner.kt:33)
        at MainKt$main$1.invokeSuspend(Main.kt:19)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:271)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at MainKt.main(Main.kt:8)
        at MainKt.main(Main.kt)

C:\Users\boris\Downloads\volynov\build\Volynov-0.0.0>pause
```

**Desktop**
 - OS Win10
 - Java 8

**Additional context**
http://forum.lwjgl.org/index.php?topic=6428.0

**Comment by Blaarkies** [comment]
https://kotlinlang.org/docs/tutorials/native/using-command-line-compiler.html

or try packaging a Java11 into the release?
